Algoritmo DESCUENTO_20
	definir VAP,VAT como real
	VAT=0
	VAP=0
	ESCRIBIR"INGRESE EL VALOR DE LA COMPRA"
	LEER VAP
	SI VAP <=1000
		ESCRIBIR "EL VALOR FINAL A PAGAR ES " C
	SiNo
		VAT= VAP-(VAP*0.2)
		ESCRIBIR "EL VALOR DE LA COMPRA ES " VAP " BS" " Y OBTUVO UN DESCUENTO DEL 20 PORCIENTO "
		ESCRIBIR "EL VALOR FINAL A PAGAR ES " VAT " BS "
	FinSi
FinAlgoritmo
